---
schema:
  procedures: {}
  tables:
    dbix_class_deploymenthandler_versions:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - version
          match_type: ''
          name: dbix_class_deploymenthandler_versions_version
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        ddl:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: ddl
          order: 3
          size:
            - 0
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        upgrade_sql:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: upgrade_sql
          order: 4
          size:
            - 0
        version:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: version
          order: 2
          size:
            - 50
      indices: []
      name: dbix_class_deploymenthandler_versions
      options: []
      order: 1
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    package: &1 !!perl/hash:Exploration::Afterlife::Schema
      class_mappings:
        DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult: __VERSION
        Exploration::Afterlife::Schema::Result::Article: Article
        Exploration::Afterlife::Schema::Result::Category: Category
        Exploration::Afterlife::Schema::Result::UserLevel: UserLevel
        Exploration::Afterlife::Schema::Result::Users: Users
      source_registrations:
        Article: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            article_id:
              auto_increment: 1
              data_type: integer
            category_id:
              _inflate_info:
                deflate: !!perl/code '{ "DUMMY" }'
                inflate: !!perl/code '{ "DUMMY" }'
              data_type: integer
              is_foreign_key: 1
            content:
              data_type: text
            date_posted:
              data_type: integer
            posted_by_user_id:
              _inflate_info:
                deflate: !!perl/code '{ "DUMMY" }'
                inflate: !!perl/code '{ "DUMMY" }'
              data_type: integer
              is_foreign_key: 1
            title:
              data_type: text
          _columns_info_loaded: 0
          _ordered_columns:
            - article_id
            - content
            - title
            - date_posted
            - category_id
            - posted_by_user_id
          _primaries: &2
            - article_id
          _relationships:
            category:
              attrs:
                accessor: multi
                cascade_copy: 1
                cascade_delete: 1
                join_type: LEFT
              class: Exploration::Afterlife::Schema::Result::Category
              cond:
                foreign.category_id: self.category_id
              source: Exploration::Afterlife::Schema::Result::Category
            category_id:
              attrs:
                accessor: filter
                is_foreign_key_constraint: 1
                undef_on_null_fk: 1
              class: Exploration::Afterlife::Schema::Result::Category
              cond:
                foreign.category_id: self.category_id
              source: Exploration::Afterlife::Schema::Result::Category
            posted_by:
              attrs:
                accessor: multi
                cascade_copy: 1
                cascade_delete: 1
                join_type: LEFT
              class: Exploration::Afterlife::Schema::Result::Users
              cond:
                foreign.user_id: self.posted_by_user_id
              source: Exploration::Afterlife::Schema::Result::Users
            posted_by_user_id:
              attrs:
                accessor: filter
                is_foreign_key_constraint: 1
                undef_on_null_fk: 1
              class: Exploration::Afterlife::Schema::Result::Users
              cond:
                foreign.user_id: self.posted_by_user_id
              source: Exploration::Afterlife::Schema::Result::Users
          _unique_constraints:
            primary: *2
          name: article
          result_class: Exploration::Afterlife::Schema::Result::Article
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: Article
        Category: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            category_id:
              auto_increment: 1
              data_type: integer
            category_name:
              data_type: text
          _columns_info_loaded: 0
          _ordered_columns:
            - category_id
            - category_name
          _primaries: &3
            - category_id
          _relationships:
            category:
              attrs:
                accessor: multi
                cascade_copy: 1
                cascade_delete: 1
                join_type: LEFT
              class: Exploration::Afterlife::Schema::Result::Article
              cond:
                foreign.category_id: self.category_id
              source: Exploration::Afterlife::Schema::Result::Article
          _unique_constraints:
            primary: *3
          name: category
          result_class: Exploration::Afterlife::Schema::Result::Category
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: Category
        UserLevel: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            user_level_id:
              auto_increment: 1
              data_type: integer
            user_level_name:
              data_type: text
          _columns_info_loaded: 0
          _ordered_columns:
            - user_level_id
            - user_level_name
          _primaries: &4
            - user_level_id
          _relationships:
            user_level:
              attrs:
                accessor: multi
                cascade_copy: 1
                cascade_delete: 1
                join_type: LEFT
              class: Exploration::Afterlife::Schema::Result::Users
              cond:
                foreign.user_level_id: self.user_level_id
              source: Exploration::Afterlife::Schema::Result::Users
          _unique_constraints:
            primary: *4
          name: user_level
          result_class: Exploration::Afterlife::Schema::Result::UserLevel
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: UserLevel
        Users: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            email:
              data_type: text
            firstname:
              data_type: text
            lastname:
              data_type: text
            password:
              data_type: text
            user_id:
              auto_increment: 1
              data_type: integer
            user_level_id:
              _inflate_info:
                deflate: !!perl/code '{ "DUMMY" }'
                inflate: !!perl/code '{ "DUMMY" }'
              data_type: integer
              is_foreign_key: 1
            username:
              data_type: text
          _columns_info_loaded: 0
          _ordered_columns:
            - user_id
            - user_level_id
            - username
            - password
            - lastname
            - firstname
            - email
          _primaries: &5
            - user_id
          _relationships:
            level:
              attrs:
                accessor: multi
                cascade_copy: 1
                cascade_delete: 1
                join_type: LEFT
              class: Exploration::Afterlife::Schema::Result::UserLevel
              cond:
                foreign.user_level_id: self.user_level_id
              source: Exploration::Afterlife::Schema::Result::UserLevel
            user:
              attrs:
                accessor: multi
                cascade_copy: 1
                cascade_delete: 1
                join_type: LEFT
              class: Exploration::Afterlife::Schema::Result::Article
              cond:
                foreign.posted_by_user_id: self.user_id
              source: Exploration::Afterlife::Schema::Result::Article
            user_level_id:
              attrs:
                accessor: filter
                is_foreign_key_constraint: 1
                undef_on_null_fk: 1
              class: Exploration::Afterlife::Schema::Result::UserLevel
              cond:
                foreign.user_level_id: self.user_level_id
              source: Exploration::Afterlife::Schema::Result::UserLevel
          _unique_constraints:
            primary: *5
            username:
              - username
          name: users
          result_class: Exploration::Afterlife::Schema::Result::Users
          resultset_attributes: {}
          resultset_class: DBIx::Class::ResultSet
          schema: *1
          source_name: Users
        __VERSION: !!perl/hash:DBIx::Class::ResultSource::Table
          _columns:
            ddl:
              data_type: text
              is_nullable: 1
            id:
              data_type: int
              is_auto_increment: 1
            upgrade_sql:
              data_type: text
              is_nullable: 1
            version:
              data_type: varchar
              size: 50
          _columns_info_loaded: 0
          _ordered_columns:
            - id
            - version
            - ddl
            - upgrade_sql
          _primaries: &6
            - id
          _relationships: {}
          _unique_constraints:
            dbix_class_deploymenthandler_versions_version:
              - version
            primary: *6
          name: dbix_class_deploymenthandler_versions
          result_class: DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResult
          resultset_attributes: {}
          resultset_class: DBIx::Class::DeploymentHandler::VersionStorage::Standard::VersionResultSet
          schema: *1
          source_name: __VERSION
      storage: !!perl/hash:DBIx::Class::Storage::DBI::SQLite
        _conn_pid: 75756
        _connect_info:
          - DBI:SQLite:/Users/ashleyp/Google Drive/Exploration-Afterlife/share/exploration-afterlife-schema.db
          - ''
          - ''
        _dbh: !!perl/hash:DBI::db {}
        _dbh_autocommit: 1
        _dbh_details: {}
        _dbh_gen: 0
        _dbi_connect_info:
          - DBI:SQLite:/Users/ashleyp/Google Drive/Exploration-Afterlife/share/exploration-afterlife-schema.db
          - ''
          - ''
          - &7
            AutoCommit: 1
            PrintError: 0
            RaiseError: 1
            ShowErrorStatement: 1
        _dbic_connect_attributes: *7
        _driver_determined: 1
        _in_do_block: 0
        _sql_maker: ~
        _sql_maker_opts: {}
        savepoints: []
        schema: *1
        transaction_depth: 0
    sources:
      - __VERSION
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11010
