# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Exploration Afterlife"

# plugins
plugins:
  DBIC:
    default:
      dsn: dbi:SQLite:dbname=share/exploration-afterlife-schema.db
      schema_class: Exploration::Afterlife::Schema


# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

template: xslate
engines:
  xslate:
    cache_dir:  .xslate_cache/
    cache: 1
    extension: tx
    syntax: TTerse
    header:
      - layout/header.tx
    footer:
      - layout/footer.tx
    module:
      - Text::Xslate::Bridge::TT2Like
